environment:
  name: staging
  service:
    name: hydra-main
    cluster: core
    certificate_arn: arn:aws:acm:us-west-2:773713188930:certificate/c2979a7a-7b84-43ed-b3a7-24b0256a1b9f
    root_domain: staging.reactioncommerce.com
    dns_name: reaction-hydra-main
    desired_task_count: 1
    min_task_count: 0
    max_task_count: 2
    min_healthy_percent: 100
    max_percent: 200
    alb_type: internet-facing
    alb_listener_port: 80
    alb_listener_path: /
    alb_health_check_path: /health
    task-definition:
      name: staging-hydra-main
      containers:
      - name: nginx
        cpu: 100
        memory: 256
        port_mappings:
        - container_port: 8080
          host_port: 8080
        image: reactioncommerce/reaction-nginx
        image_tag: hydra
        links:
        - hydra
        env_params:
        - name: PROXY_URL
        - name: NGINX_LISTEN_PORT
      - name: hydra
        cpu: 100
        memory: 256
        command:
        - serve
        - all
        - "--dangerous-force-http"
        port_mappings:
        - container_port: 4444
        - container_port: 4445
        - container_port: 5555
        image: oryd/hydra
        image_tag: v1.0.0-beta.9-alpine
        env_params:
        - name: OAUTH2_ISSUER_URL
        - name: OAUTH2_CONSENT_URL
        - name: OAUTH2_LOGIN_URL
        - name: DATABASE_URL
        - name: OAUTH2_SHARE_ERROR_DEBUG
        - name: SYSTEM_SECRET
        - name: OIDC_SUBJECT_TYPES_SUPPORTED
        - name: OIDC_SUBJECT_TYPE_PAIRWISE_SALT
